# Site settings
title: "EMNLP 16: Structured Prediction for Natural Language Processing"
email: kw@kwchang.net
#description: "EMNLP 16: Structured Prediction for Natural Language Processing"
baseurl: "/structuredprediction/"
url: "http://harvardnlp.github.io/structuredprediction/"
#twitter_username: jekyllrb
#github_username:  jekyll

# Build settings
markdown: kramdown
permalink: pretty
